# Generated by Django 3.2.13 on 2022-04-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noti',
            table='dashview_notify',
        ),
    ]
