# Generated by Django 3.2.13 on 2022-04-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('filename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'report_data',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='noti',
            table='dashview_notify',
        ),
    ]
