# Generated by Django 4.0.4 on 2022-05-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_view', '0002_alter_noti_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('item', models.CharField(choices=[('aerosol', 'aerosol'), ('alcohol', 'alcohol'), ('awl', 'awl'), ('axe', 'axe'), ('battery', 'battery'), ('bat', 'bat'), ('bullet', 'bullet'), ('chisel', 'chisel'), ('electronic cigarettes(liquid)', 'electronic cigarettes(liquid)'), ('electronic cigarettes', 'electronic cigarettes'), ('firecracker', 'firecracker'), ('gunparts', 'gunparts'), ('gun', 'gun'), ('hammer', 'hammer'), ('handcuffs', 'handcuffs'), ('hdd(external)', 'hdd(external)'), ('hdd', 'hdd'), ('knife', 'knife'), ('laptop', 'laptop'), ('lighter', 'lighter'), ('liquid', 'liquid'), ('match', 'match'), ('metalpipe', 'metalpipe'), ('nailclippers', 'nailclippers'), ('plier', 'plier'), ('prtablegas', 'prtablegas'), ('saw', 'saw'), ('scissors', 'scissors'), ('screwdriver', 'screwdriver'), ('smartphone', 'smartphone'), ('solidfuel', 'solidfuel'), ('spanner', 'spanner'), ('ssd', 'ssd'), ('supplymentarybattery', 'supplymentarybattery'), ('tabletpc', 'tabletpc'), ('thinner', 'thinner'), ('throwing knife', 'throwing knife'), ('usb', 'usb'), ('zippooilm', 'zippooil')], max_length=50)),
                ('confidence', models.FloatField()),
                ('filename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'report_data',
                'managed': True,
            },
        ),
    ]
