# Generated by Django 4.0.4 on 2022-05-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_view', '0004_uploadfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'managed': True},
        ),
    ]
